// <auto-generated/>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Integration tests rely on descriptive naming and do not require XML documentation.")]
[assembly: SuppressMessage("Documentation", "CS1591", Justification = "Integration tests rely on descriptive naming and do not require XML documentation.")]
