# Workflow temporalmente deshabilitado mientras se actualiza la infraestructura de CI.
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    # Condición fija para evitar que el workflow se ejecute hasta completar la revisión.
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ProyectoBase.sln

      - name: Build
        run: dotnet build ProyectoBase.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ProyectoBase.sln --no-build --configuration Release --verbosity normal
